package entity;
// Generated Oct 27, 2023, 5:12:04 PM by Hibernate Tools 5.2.13.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Author generated by hbm2java
 */
@Entity
@Table(name = "Author")
public class Author implements java.io.Serializable {

	private int authorId;
	private String authorName;
	private Set<Book> books = new HashSet<Book>(0);

	public Author() {
	}

	public Author(int authorId) {
		this.authorId = authorId;
	}

	public Author(int authorId, String authorName, Set<Book> books) {
		this.authorId = authorId;
		this.authorName = authorName;
		this.books = books;
	}

	@Id

	@Column(name = "author_id", unique = true, nullable = false)
	public int getAuthorId() {
		return this.authorId;
	}

	public void setAuthorId(int authorId) {
		this.authorId = authorId;
	}

	@Column(name = "author_name", length = 25)
	public String getAuthorName() {
		return this.authorName;
	}

	public void setAuthorName(String authorName) {
		this.authorName = authorName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "author")
	public Set<Book> getBooks() {
		return this.books;
	}

	public void setBooks(Set<Book> books) {
		this.books = books;
	}

}
