package entity;
// Generated Oct 28, 2023, 5:11:28 PM by Hibernate Tools 5.2.13.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "Book")
public class Book implements java.io.Serializable {

	private String isbn;
	private Author author;
	private String title;

	public Book() {
	}

	public Book(String isbn) {
		this.isbn = isbn;
	}

	public Book(String isbn, Author author, String title) {
		this.isbn = isbn;
		this.author = author;
		this.title = title;
	}

	@Id

	@Column(name = "isbn", unique = true, nullable = false, length = 25)
	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "author_id")
	public Author getAuthor() {
		return this.author;
	}

	public void setAuthor(Author author) {
		this.author = author;
	}

	@Column(name = "title", length = 20)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

}
